name: Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3']
        rails-version: ['7.0', '7.1', '8.0']
        importmap-rails-version: ['2.0', '1.2']
      fail-fast: false

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails-version }}__importmap_rails_version_${{ matrix.importmap-rails-version }}.gemfile

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Bundler
      run: bundle install
    - name: Run tests
      run: bin/test
